# Default values for hawkbit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: hawkbit-update-server-azure
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ssl-redirect: "true"
  paths:
    - /
  hosts:
    - hawkbit.westeurope.cloudapp.azure.com
  tls:
    secretName: tls-secret-hawkbit

resources:
  requests:
    cpu: 100m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
