apiVersion: v1
kind: Secret
metadata:
  name: hawkbit-infra-secrets
type: Opaque
data:
  db-password: {{ .Values.db.password  | b64enc | quote}}
  db-username: {{ .Values.db.username  | b64enc | quote}}
  db-url: {{ .Values.db.url  | b64enc | quote}}
  storage-url: {{ .Values.storage.url  | b64enc | quote}}
  event-hubs-connection-string: {{ .Values.eventHubs.connectionString  | b64enc | quote}}
  eventhubs-namespace: {{ .Values.eventHubs.namespace  | b64enc | quote}}
  insights-key: {{ .Values.insights.key  | b64enc | quote}}